//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WamesRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        public int employee_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public Nullable<decimal> salary { get; set; }
        public int department_id { get; set; }
        public int position_id { get; set; }
        public int team_id { get; set; }
    
        public virtual departments departments { get; set; }
        public virtual positions positions { get; set; }
        public virtual Team Team { get; set; }
    }
}
